### ISSUE TITLE
`walk.js` aborts with error if input scripts contains ES6 code

### ISSUE THREAD

**Issue by sergejmueller** [nolanlawson/optimize-js#3]
Perhaps because `walk.js` does not support ES6?

Example: [start.js.txt](https://github.com/nolanlawson/optimize-js/files/479966/start.js.txt)

```bash
TypeError: types[type] is not a function
    at walk (/usr/local/lib/node_modules/optimize-js/node_modules/walk-ast/lib/walk.js:17:16)
    at Object.skip (/usr/local/lib/node_modules/optimize-js/node_modules/walk-ast/lib/types.js:293:3)
    at walk (/usr/local/lib/node_modules/optimize-js/node_modules/walk-ast/lib/walk.js:17:16)
    at Object.exports.BinaryExpression.exports.LogicalExpression.exports.AssignmentExpression (/usr/local/lib/node_modules/optimize-js/node_modules/walk-ast/lib/types.js:243:3)
    at walk (/usr/local/lib/node_modules/optimize-js/node_modules/walk-ast/lib/walk.js:17:16)
    at Object.skip (/usr/local/lib/node_modules/optimize-js/node_modules/walk-ast/lib/types.js:293:3)
    at walk (/usr/local/lib/node_modules/optimize-js/node_modules/walk-ast/lib/walk.js:17:16)
    at Object.exports.ExpressionStatement (/usr/local/lib/node_modules/optimize-js/node_modules/walk-ast/lib/types.js:32:3)
    at walk (/usr/local/lib/node_modules/optimize-js/node_modules/walk-ast/lib/walk.js:17:16)
    at Object.skip (/usr/local/lib/node_modules/optimize-js/node_modules/walk-ast/lib/types.js:293:3)
```

**Comment by nolanlawson** [comment]
I'm using acorn and acorn-walk. Maybe there's a way to make it support ES6?

**Comment by sergejmueller** [comment]
I don't know. A another acorn-walk plugin? https://npmdaily.com/search/acorn

**Comment by austinkelleher** [comment]
This may not work for your use case, but I transpile to ES5 using Babel and then use optimize-js.

**Comment by nolanlawson** [comment]
@rich-harris would switching to https://www.npmjs.com/package/estree-walker solve this?

**Comment by Rich-Harris** [comment]
@nolanlawson yes

**Comment by sanex3339** [comment]
esprima has nice support of es6 and es7
https://github.com/jquery/esprima
https://github.com/estools/estraverse
https://github.com/estools/escodegen

**Comment by ideaterminal** [comment]
this is already patched with the use of estree-walker.

**Comment by benderTheCrime** [comment]
Question: wouldn't it just be possible to give acorn different options?
